baseurl: https://blog.emptynessof.space/inv
RelativeURLs: true
CanonifyURLs: true
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Inv's Blog
publishdir: /var/blogs/inv 

# Change it to your Disqus shortname before using
#disqusShortname: hugo-theme-stack

# GA Tracking ID
#googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

taxonomies:
    category: categories
    series: series
    tag: tags

params:
    mainSections:
        - post
        - series
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText: 

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 
        subtitle: A blog.
        avatar:
            enabled: true
            local: true
            src: images/avatar.png

    article:
        math: false
        toc: false
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances
        utterances:
            repo: InversionSpaces/blog
            issueTerm: pathname
            label: utterances

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              icon: home
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/InversionSpaces/
          params:
            icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
